name: Sync to S3

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Version
      run: | 
        REV=$(git rev-parse HEAD)
        jq -nc --arg rev "$REV" '{ version: $rev }' > version.json
        sed -i "s/__VERSION__/$REV/g" index.html

    - name: Sync folder to S3
      run: aws s3 sync . s3://maths.codingtony.com --exclude '*' --include '*.js' --include '*.html' --include '*.css'